### ISSUE TITLE
opprett_kunde() - Legg til dropdown for postnr

### ISSUE THREAD

**Issue by DanielTangnes** [DanielTangnes/tverrfaglig-pr-ve#16]
postnr som blir satt på bruker må være et postnr som ligger i poststed tabell.
Lag dropdown meny for å velge godkjent postnr når man skal opprette bruker

**Comment by CSkogbakken** [comment]
Mulig løsning med liste, sier ikke så mye om SQL:
https://stackoverflow.com/questions/45738045/tkinter-dropdown-menu-from-sql-table

**Comment by Ekvivokk** [comment]
Dropdown med auto population og sjekk av postnummer

**Comment by Ekvivokk** [comment]
> Dropdown med auto population og sjekk av postnummer

Fikset dropdown meny som heter postnummer fra listen vi har laget i databasen, og fått implementert det grunnleggende med autocomplete, ønsker fortsatt å forbedre dette noe.

**Comment by Ekvivokk** [comment]
Ser ut som å vise dropdown mens man skriver inn tekst kan gjøres, men det blir hacky, så jeg tenker at det droppes https://coderslegacy.com/searchable-combobox-in-tkinter/

**Comment by Ekvivokk** [comment]
Implementert
