### ISSUE TITLE
Utforske og sette opp stored procedures i Databasen

### ISSUE THREAD

**Issue by CSkogbakken** [DanielTangnes/tverrfaglig-pr-ve#2]
Sette opp stored procedures i databasen etter oppgaven.

**Comment by DanielTangnes** [comment]
https://www.w3schools.com/sql/sql_stored_procedures.asp#:~:text=Stored%20Procedure%20With%20One%20Parameter

**Comment by CSkogbakken** [comment]
Stored procedures fungerer som vi forventet, er bare en vanlig spørring som er lagret i databasen. (Tenk funksjoner i Python). Men MySQL har tydligvis en litt egen måte og sette det opp på som W3Schools ikke prater om. Denne beskriver det ganske bra: https://www.sqlshack.com/learn-mysql-the-basics-of-mysql-stored-procedures/

**Comment by CSkogbakken** [comment]
Spørringer vi trenger å kjøre mot basen:
1. Hente liste over alle ansatte.
2. Hente liste over alle varer på lager; varenummer, navn, antall og pris.
3. Hente liste over alle ordre.
4. Hente detaljer på en spesifikk ordre; varer, antall av hver vare, pris pr vare, totalpris pr type vare, kunde m/navn og adresse og totalpris på ordre.
5. Hente alle kunder i databaasen

**Comment by CSkogbakken** [comment]
Alle spørringer nevnt over funker nå som Stored Procedures.

Gjenstår og få lagt spørringer/prosedyrer som kan oppdatere kundebasen med nye kunder og slette kunder.
