### ISSUE TITLE
Velge spesifikk ordre

### ISSUE THREAD

**Issue by Ekvivokk** [DanielTangnes/tverrfaglig-pr-ve#20]
Kunne velge en spesifikk ordre og vise hva slags varer, antall av hver vare som har blitt solgt, pris pr.vare, pris ganger antall, kunde m/navn og adresse og total pris.  

Det allerede lagd kode for enkel funksjon fra å hente ordre, resten må fikses.

**Comment by DanielTangnes** [comment]
Lagt til popup som viser ordredetaljer.
