### ISSUE TITLE
Slette og opprette kunder i basen fra programmet

### ISSUE THREAD

**Issue by CSkogbakken** [DanielTangnes/tverrfaglig-pr-ve#7]

**Comment by DanielTangnes** [comment]
DELETE FROM table_name WHERE condition;

**Comment by DanielTangnes** [comment]
Lagt til funksjon for sletting og oppretting av kunder.
Mangler å ta i bruk stored procedure for oppretting av kunder

**Comment by DanielTangnes** [comment]
Opprettet proc for oppretting og sletting av brukere
